name: Core
main: me.declyn.core.Core
version: 1.3
commands:
  alert:
    aliases: ["broadcast", "bc"]
  chat:
  clearinventory:
    aliases: ["clearinv", "ci", "clear"]
  fly:
    aliases: ["fly"]
  freeze:
    aliases: ["screenshare", "ss"]
  gamemode:
    aliases: ["gm"]
  list:
    aliases: ["online"]
  message:
    aliases: ["msg", "m", "privatemessage", "pm", "tell", "t", "whipser", "w"]
  ping:
  rank:
  reply:
    aliases: ["r"]
  report:
  request:
    aliases: ["helpop"]
  setslots:
    aliases: ["setmaxslots", "setmaxplayers"]
  staffchat:
    aliases: ["sc"]
  teleport:
    aliases: ["tp"]
  teleporthere:
    aliases: ["tphere", "summon", "s"]
  user:
  vanish:
    aliases: ["v"]